<?php
namespace frontend\controllers;

class IndexController extends CommonController
{
    //无需验证csrf的动作
    public $ignore_csrf='index/send-verify,';
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if(stripos($this->ignore_csrf,\Yii::$app->requestedRoute)!==false){
            $this->enableCsrfValidation=false;
        }
    }

//    public $enableCsrfValidation=false;
    public function actionIndex()
    {
        return '前台首页';
    }
    //发送验证码
    public function actionSendVerify()
    {
        $this->enableCsrfValidation=false;
        $phone = $this->request->post('phone');
        $type = $this->request->post('type');
        if(empty($phone)) throw new \yii\base\UserException('请输入手机号码');
        if($type=='' || !is_numeric($type)) throw new \yii\base\UserException('发送类型异常.');

        try{
            \common\models\Sms::sendMail($phone,$type);
            return $this->asJson(['code'=>1,'msg'=>'发送成功']);
        }catch (\Exception $e){
            return $this->asJson(['code'=>0,'msg'=>$e->getMessage()]);
        }
    }
}