<?php
namespace  wechat\controllers;

use yii\web\Controller;

class CommonController extends Controller
{
    public $user_id = 0;

    public $is_need_login = false;
    protected $ignore_action = '';


    /**
     *
     * @var \yii\web\Request
     * */
    public $request;


    public function init()
    {
        parent::init();
        $user_info =\Yii::$app->session->get('user_info');
        $this->request = \Yii::$app->request;
        if(!empty($user_info)){
            $this->user_id = isset($user_info['user_id'])?$user_info['user_id']:0;
        }
//        var_dump($_SESSION);var_dump($_COOKIE);exit;
    }


    public function beforeAction($action)
    {
        parent::beforeAction($action);
        if($this->is_need_login){
            if(!$this->user_id && strpos($this->ignore_action,$action->id)===false){
                if($this->request->isAjax){
                    //需要登录才能访问
                    \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                    \Yii::$app->response->data = array(
                        'code' => 0,
                        'msg' => '请先登录',
                        'url' => \yii\helpers\Url::to(['index/login'])
                    );
                    return false;
                }else{
                    //需要登录才能访问
                    $this->redirect(\yii\helpers\Url::to(['index/login']));
                    return false;
                }
            }
        }


        return true; // TODO: Change the autogenerated stub
    }
}