<?php
namespace wechat\controllers;


class OrderController extends CommonController
{
    public $is_need_login = true;
    /**
     * 用户模型
     * @var \common\models\User
     * */
    protected $user_model;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->user_model = \common\models\User::findOne($this->user_id);
        if(empty($this->user_model)){
            $this->user_id = 0;
        }
    }

    public function actionInfo($is_return=false)
    {
        $gid = $this->request->isGet?$this->request->get('gid'):$this->request->post('gid');
        $num = $this->request->isGet?$this->request->get('num',1):$this->request->post('num',1);

        //地址
        $model_addr = \common\models\UserAddr::find()->where(['uid'=>$this->user_id])->orderBy('is_default desc, id desc')->one();

        $model = new \common\models\Order();
        //检出订单信息
        list($goods_info,$money) = $model->checkOrderInfo($this->user_model,$gid,$num);
        /**/
        if($is_return){
            return [$model,$goods_info,$money,$model_addr];
        }
        //支付方式
        $pay_way = \common\models\Order::getPayWay();
        return $this->render('info',[
            'gid' => $gid,
            'num' => $num,
            'model_addr' => $model_addr,
            'goods_info' => $goods_info,
            'money' => $money,
            'pay_way' => $pay_way,
        ]);
    }

    //订单地址
    public function actionConfirm()
    {
        //合同信息
        $contract = $this->request->post('contract');
        //订单数据
        list($order_model,$goods_info,$money,$model_addr) = $this->actionInfo(true);
        try{
            $order_model->confirm($this->user_model,$goods_info,$money,$model_addr,$contract);
        }catch (\Exception $e){
            throw new \yii\base\UserException($e->getMessage());
        }
        return $this->asJson(['code'=>1,'msg'=>'创建订单成功']);


    }

}